"""Add ForeignKey to clients.user_id

Revision ID: e941b7c1b617
Revises: d31d99e895cc
Create Date: 2025-06-19 00:01:31.078736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e941b7c1b617'
down_revision: Union[str, None] = 'd31d99e895cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_user_id_fkey', 'clients', type_='foreignkey')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('clients_user_id_fkey', 'clients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
